spring.application.name=api-gateway

# API Gateway chay port 9000 (8080/8081/8082 da duoc cac service dung)
server.port=9000

# URL cac service dich (co the doi theo moi truong, khong can sua code)
services.product.url=http://localhost:8080
services.order.url=http://localhost:8081
services.inventory.url=http://localhost:8082
